In [31]:
import pandas as pd
import plotly.express as px

In [32]:
df = px.data.gapminder()

In [33]:
df[df['country'] == 'India']

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
696,India,Asia,1952,37.373,372000000,546.565749,IND,356
697,India,Asia,1957,40.249,409000000,590.061996,IND,356
698,India,Asia,1962,43.605,454000000,658.347151,IND,356
699,India,Asia,1967,47.193,506000000,700.770611,IND,356
700,India,Asia,1972,50.651,567000000,724.032527,IND,356
701,India,Asia,1977,54.208,634000000,813.337323,IND,356
702,India,Asia,1982,56.596,708000000,855.723538,IND,356
703,India,Asia,1987,58.553,788000000,976.512676,IND,356
704,India,Asia,1992,60.223,872000000,1164.406809,IND,356
705,India,Asia,1997,61.765,959000000,1458.817442,IND,356
706,India,Asia,2002,62.879,1034172547,1746.769454,IND,356
707,India,Asia,2007,64.698,1110396331,2452.210407,IND,356

In [34]:
df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [35]:
df2=df[df['year'] == 2007]

In [36]:
px.scatter(data_frame=df2,x='gdpPercap',y='lifeExp',size='pop',color='continent',title='GDP Per Capita vs Life Expectancy in 2007',labels={'gdpPercap':'GDP Per Capita','lifeExp':'Life Expectancy'},template='plotly_dark')

In [37]:
df_egypt=df[df['country'] == 'Egypt']

In [38]:
px.line(data_frame=df_egypt,x='year',y='lifeExp',title='Life Expectancy in Egypt',markers=True,labels={'lifeExp':'Life Expectancy','year':'Year'},template='plotly_dark')

In [28]:
df_tips = px.data.tips()
df_tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [29]:
px.pie(data_frame=df_tips,names='day',values='total_bill',title='Total Bill Distribution by Day',template='plotly_dark',labels={'day':'Day of the Week','total_bill':'Total Bill'},color_discrete_sequence=px.colors.qualitative.Pastel,hole=0.6)

In [30]:
px.bar(data_frame=df_tips,x='smoker',y='total_bill',color='day',title='Total Bill by Smoker Status and Day',labels={'smoker':'Smoker Status','total_bill':'Total Bill','day':'Day of the Week'},template='plotly_dark')

In [39]:
px.bar(data_frame=df_tips,x='day',y='total_bill',color='smoker',title='Total Bill by Day and Smoker Status',labels={'day':'Day of the Week','total_bill':'Total Bill','smoker':'Smoker Status'},template='plotly_dark')

In [44]:
temp= df_tips.groupby('day')['total_bill'].sum().reset_index()

In [45]:
temp

    day  total_bill
0   Fri      325.88
1   Sat     1778.40
2   Sun     1627.16
3  Thur     1096.33

In [48]:
px.bar(data_frame=temp,x='day',y='total_bill',title='Total Bill by Day and Smoker Status',labels={'day':'Day of the Week','total_bill':'Total Bill','smoker':'Smoker Status'},template='plotly_dark')

In [49]:
px.choropleth(data_frame=df2,locations='iso_alpha',color='pop',hover_name='country',title='Global Life Expectancy in 2007',color_continuous_scale=px.colors.sequential.Plasma,labels={'lifeExp':'Life Expectancy','iso_alpha':'Country Code'},template='plotly_dark')